### ISSUE TITLE
Search results ordering: favour direct hits over others

### ISSUE THREAD

**Issue by keithamus** [librariesio/support#1]
When searching for a keyword - for example "express", despite there being a package who's name is exactly "express", it appears 7th on the list:

![screen shot 2015-03-16 at 13 17 36](https://cloud.githubusercontent.com/assets/118266/6666706/dc7f1fd0-cbde-11e4-9d38-cd25eefd386c.PNG)

Direct hits like this should probably appear at the top of the list. Like so:

![screen shot 2015-03-16 at 13 18 34](https://cloud.githubusercontent.com/assets/118266/6666721/faf8472a-cbde-11e4-812c-de80b28005e2.PNG)

**Comment by andrew** [comment]
Yep, I'm still trying to bend elasticsearch to do reliably!

**Comment by Kreozot** [comment]
You're lucky. "d3" was been found on second page =]

**Comment by andrew** [comment]
Pretty sure it does this now:

https://libraries.io/search?q=d3
https://libraries.io/search?q=express
