### ISSUE TITLE
Incorrect "latest version" information for Rails in Gemfile.lock table

### ISSUE THREAD

**Issue by tomnatt** [librariesio/support#101]
Rails and many related Action\* and Active\* gems are reporting the incorrect latest versions. 

For example here:
https://libraries.io/github/tomnatt/show-tell

I am seeing latest stable Rails as 3.2.22.4.

**Comment by andrew** [comment]
I'm going to close this as a duplicate of https://github.com/librariesio/libraries.io/issues/337
