### ISSUE TITLE
Duplicate package

### ISSUE THREAD

**Issue by ale5000-git** [librariesio/support#105]
There are 2 different pages for the same thing:
https://libraries.io/pypi/PyCompatLayer
https://libraries.io/pypi/pycompatlayer

**Comment by ale5000-git** [comment]
pypi.python.org does index packages in a case insensitive way, and it do a redirect (HTTP/1.1 301 Moved Permanently) whe you request it with a not-preferred case, you should detect this and store only the preferred case.

You can see the redirect here: https://pypi.python.org/pypi/pycompatlayer

**Comment by andrew** [comment]
That's definitely a bug, will investigate that, thanks for the heads up

**Comment by andrew** [comment]
Have investigated this, the code now handles redirects and always takes the proper case, I'm currently running a script to clean up the incorrectly cased duplicates, thanks for reporting!
