### ISSUE TITLE
Do not support Python requirements files with spaces

### ISSUE THREAD

**Issue by ale5000-git** [librariesio/support#107]
Space are allowed in requirements files but librariesio do not support them.

Example: https://github.com/ale5000-git/tingle/blob/master/requirements/requirements.txt

**Comment by andrew** [comment]
Fixed in https://github.com/librariesio/librarian-parsers/commit/e1cfcea78f476a8b0fec86098d8ffec99397de62

https://libraries.io/github/ale5000-git/tingle#dependencies

**Comment by ale5000-git** [comment]
@andrew: Could you please fix also [here](https://libraries.io/github/ale5000-git/adb-toolbox) and [here](https://libraries.io/github/BenBaltz/mission-improbable)?

**Comment by andrew** [comment]
@ale5000-git I've updated those for you now
