### ISSUE TITLE
API: per_page failing if greater than 100

### ISSUE THREAD

**Issue by bdkjones** [librariesio/support#109]
#97 and #76 (both closed) are also this issue. In those threads, the `per_page` limit was raised to `1000`. But that doesn't appear to be the case, as this request will still return a 404:

    https://libraries.io/api/search?platforms=Bower&per_page=1000&page=2&api_key=[mykey]"

But as soon as `per_page` is reduced to 100, it works great:

    https://libraries.io/api/search?platforms=Bower&per_page=100&page=2&api_key=[mykey]"

*Any* value for `per_page` that is `>100` will produce the 404. Can someone advise?

**Comment by bdkjones** [comment]
It DOES appear that the API is now returning results when `page` is greater than 100. The API documentation page also states that `per_page` is limited to `100`. If that's the case, will the API now correctly return results for any page? (Previously, it cut off at 100 and a request for a page greater than 100 would fail)

**Comment by andrew** [comment]
Yeah sorry that was a typo, the `page` limit has been increased to 1000 but `per_page` is still limited to 100, so you can page through a maximum of `100,000` results now
