### ISSUE TITLE
Feature request: allow bulk subscription to libraries

### ISSUE THREAD

**Issue by volans-** [librariesio/support#11]
First of all kudos for the great project, I like the idea a lot!

I think it will be very useful for all the users to be able paste in a text area the list of libraries they want to subscribe for bulk subscription, specifying the programming language.

Most programming languages have files that list all the dependencies and probably many people would love to get notified when a new version of a library that they are dependent on is out in a centralized way for multiple languages so that they can track both their backend as well as their UI dependencies.

My proposal is to support the parsing of those files, like requires for Python, package.json for NPM, Gemfile, etc... to automatically subscribe me to all the libraries in the file with a precise match of the name only looking in that programming language list.

For the one that are not present/doesn't match I would report them in the UI as missing and automatically add to the list of potential additions.

For the ones that matches multiple items you could show all of them with a subscribe button on the side to allow a quick manual choice by the user.

**Comment by andrew** [comment]
It's like you read my mind! I'm currently working on this exact feature, I'll let you know when it's ready for testing.

**Comment by volans-** [comment]
@andrew that's awesome! I'd be glad to help testing it. Thanks

**Comment by volans-** [comment]
@andrew by any chance any news about this? Is still in the roadmap?

**Comment by andrew** [comment]
@volans- it's almost ready, drop me an email if you'd like to try out the beta: support@libraries.io

**Comment by andrew** [comment]
I've :ship: this now https://libraries.io/repositories :tada:
