### ISSUE TITLE
Turbolinks 5 is not depricated

### ISSUE THREAD

**Issue by kmmbvnr** [librariesio/support#112]
The page https://libraries.io/npm/turbolinks stated that turbolinks project is deprecated, but actually, the turbolinks 5.0 is the recommended package, and the deprecated one is turbolinks-classic

https://github.com/turbolinks/turbolinks
https://www.npmjs.com/package/turbolinks

**Comment by andrew** [comment]
@kmmbvnr thanks for letting me know, I've fixed that now
