### ISSUE TITLE
Several issues with Nanoc ruby gem

### ISSUE THREAD

**Issue by ddfreyne** [librariesio/support#113]
The [SourceRank Breakdown for the nanoc gem](https://libraries.io/rubygems/nanoc/sourcerank) has a few issues:

* A GitHub repository is present, but SourceRank does not think so
* A Readme file is present, but SourceRank does not think so
* Nanoc follows SemVer, but SourceRank does not think so
* GitHub stars is incorrectly zero
* Number of contributors is incorrectly zero

**Comment by andrew** [comment]
@ddfreyne looks like a bug in cache invalidation (or lack of), I've fixed that in https://github.com/librariesio/libraries.io/commit/a8bf5907a9348cc82be010d7d00303300252f94b and updated the sourcerank for nanoc: https://libraries.io/rubygems/nanoc/sourcerank

As for SemVer, you've got 19 versions that don't follow semver correctly:
```
"3.0.0a1", "3.0.0a2", "3.5.0b1", "3.5.0b2", "3.6.10.1", "4.0.0a1", "4.0.0a2", 
"4.0.0b1", "4.0.0b2", "4.0.0b3", "4.0.0b4", "4.0.0rc1", "4.0.0rc2", "4.0.0rc3", 
"4.1.0a1", "4.1.0b1", "4.1.0rc1", "4.1.0rc2", "4.2.0b1"
```

Prereleases need to be seperated by a dash: http://semver.org/#spec-item-9

**Comment by ddfreyne** [comment]
Thanks for the quick response!

Hah, I can’t believe I have (consistently) been using the wrong format for pre-releases. No idea where I got that from… (ignore 3.6.10.1—that’s a yanked exception.)

**Comment by andrew** [comment]
Yeah it's a shame that rubygems doesn't warn you about invalid semver when publishing, could help avoid that!
