### ISSUE TITLE
showdown-element is not deleted

### ISSUE THREAD

**Issue by zacharyrs** [librariesio/support#114]
[libraries.io](https://libraries.io/github/zacharyrs/showdown-element) says it is removed, however it [isn't](https://github.com/zacharyrs/showdown-element).

This is probably my fault as I deleted an old repo and renamed this one. Not sure if I need to just wait, or if I need to request help, hence posting here.

**Comment by andrew** [comment]
Thanks for letting me know, I've fixed that now

**Comment by zacharyrs** [comment]
Thanks for the quick reply! 

Unfortunately, the page still thinks it's been removed, and doesn't seem to have registered that I have a new release (which I assume is because it's flagged as removed). Any suggestions? 

Thanks in advance, 
Zach

**Comment by andrew** [comment]
@zacharyrs very strange, I've completely removed and readded it now, appears to be showing all of the correct info now.

**Comment by zacharyrs** [comment]
Thanks a bunch!
