### ISSUE TITLE
Hide public profile

### ISSUE THREAD

**Issue by danez** [librariesio/support#116]
Hello, it would be nice to be able to have the public profile from libraries.io to be hidden. A simple checkbox in the settings could do the job.

For example my profile page is indexed in google and can be found by everyone, which I do not necessarily like.
https://libraries.io/github/danez

**Comment by andrew** [comment]
@danez I've added a setting here: https://libraries.io/account

![screen shot 2016-11-21 at 3 39 05 pm](https://cloud.githubusercontent.com/assets/1060/20488916/ab7c793e-b000-11e6-8755-89e7244ee49f.png)

**Comment by danez** [comment]
Thanks
