### ISSUE TITLE
Out of date version of github repository

### ISSUE THREAD

**Issue by Luthaf** [librariesio/support#118]
I noticed that (at least one) github repository information is out of date: 

- [libraries.io](https://libraries.io/github/chemfiles/chemfiles) says " Last pushed 29 days ago"
- [github](https://github.com/chemfiles/chemfiles) says "8 days" ago

It is even worst for tags:
 - [libraries.io](https://libraries.io/github/chemfiles/chemfiles/tags) ends at 0.5.0 (6 months ago)
- [github](https://github.com/chemfiles/chemfiles/releases) ends at 0.6.3

How often are github repositorie updated ?

**Comment by andrew** [comment]
In theory github repos should be updated very soon after they are changed as Libraries is following the [firehose](https://developer.github.com/v3/activity/events/#list-public-events) but sometimes it does miss things. 

There was also a bug with syncing tags over the past couple days, I've just deployed a fix for it and have updated the chemfiles repo and am kicking off a task to update more outdated ones.

**Comment by Luthaf** [comment]
Thank for updating it!

Should I leave this open for tracking the missing updates problem ?

**Comment by andrew** [comment]
@Luthaf I'll close it for now, thanks
