### ISSUE TITLE
Remove profile

### ISSUE THREAD

**Issue by Achifaifa** [librariesio/support#119]
I didn't want to bother anyone, but I've looked around and it looks like opening an issue is the only way of doing this right now. Would you mind please removing my profile from libraries.io?

Making the use of the site opt-in instead of opt-out would be the polite way of doing this in my opinion (As opposed to displaying everyone's profile without asking)

**Comment by andrew** [comment]
You can hide your profile from the account section here: https://libraries.io/account but I'll do it for you, thanks for letting me know
