### ISSUE TITLE
api pagination fails beyond the first page

### ISSUE THREAD

**Issue by ahmadnassri** [librariesio/support#124]
**endpoint**: `/api/npm/:name/dependents`

no matter what I do, `page=2` is always an empty array, this is true for any package on `npm`, I did not test on any other platform, or endpoint.

###### examples:

```
https://libraries.io/api/npm/grunt/dependents?api_key=xxx&page=2
https://libraries.io/api/npm/grunt/dependents?api_key=xxx&per_page=2&page=2
```

**Comment by andrew** [comment]
@ahmadnassri just deploying a fix for that now, thanks for reporting

**Comment by ahmadnassri** [comment]
excellent, thank you.
