### ISSUE TITLE
Bosun.java Where?

### ISSUE THREAD

**Issue by wpengcheng** [librariesio/support#126]
https://libraries.io/github/wtelecom/collectd-opentsdb

![image](https://cloud.githubusercontent.com/assets/16982786/21539801/1a08c3a6-cde5-11e6-812f-3a03acee0607.png)

There are links to this description collectd-bosun, but I did not find where to fight Org / collectd / java / Bosun.java

**Comment by andrew** [comment]
This isn't support for individual libraries, I suggest opening an issue here: https://github.com/auxesis/collectd-opentsdb/issues
