### ISSUE TITLE
Out of date version/tag/release of github/npm repository

### ISSUE THREAD

**Issue by sandfox** [librariesio/support#127]
https://libraries.io/github/coopernurse/node-pool
and
https://libraries.io/npm/generic-pool

Both seem to be missing the latest tag/publishes (v3.1.6) for github and npm respectively.

Anything I can do to help? Or is there just a button somewhere that needs pushing? (or am I being daft and missing something?)

**Comment by andrew** [comment]
@sandfox my bad, had some downtime with the watcher services yesterday, still catching up on the previous releases, I've updated those manually for you, thanks for the heads up!

**Comment by sandfox** [comment]
Awesome, thanks!
