### ISSUE TITLE
SourceRank not shown correctly on the lib pages' sidebars

### ISSUE THREAD

**Issue by revelt** [librariesio/support#128]
It looks like the SourceRank is not being shown correctly on the single library pages. Once I click on the bubble, it shows eight points on SourceRank page, but zero on the library page:

![screen shot 2017-01-09 at 15 28 03](https://cloud.githubusercontent.com/assets/8344688/21771803/c7bb7aa4-d680-11e6-8e09-bd450ce91a0f.png)

I'm using the latest MacOS and Chrome.

**Comment by andrew** [comment]
@revelt looks like a stale cache, I've cleared that and it shows 8 in both places now, thanks for reporting!
