### ISSUE TITLE
Help me to delete personal info in librariesio

### ISSUE THREAD

**Issue by SwiftCarlos** [librariesio/support#130]
Hi,

I have a problem with my personal GitHub data on your web. The problem is that google image search link a personal old photo to this links:

https://libraries.io/github/carlosbutron/
https://libraries.io/github/carlosbutron/Swift
https://libraries.io/github/carlosbutron/repositories
https://libraries.io/github/carlbutron
https://libraries.io/github/carlbutron/swift
https://libraries.io/github/carlbutron/YorkieApp

The accounts carlbutron and carlosbutron doesn't exist. I tried to register this accounts again, signin in libraries.io and delete de info, but doesn't work.

Please, can you help me?

**Comment by andrew** [comment]
I've removed all of those now for you, thanks for letting me know
