### ISSUE TITLE
Incorrect message, "This repository is no longer available" on library

### ISSUE THREAD

**Issue by revelt** [librariesio/support#131]
Incorrect message, "This repository is no longer available" on library:
https://libraries.io/github/revelt/object-boolean-combinations

![screen shot 2017-01-16 at 14 46 42](https://cloud.githubusercontent.com/assets/8344688/21987241/9c8410b0-dbfa-11e6-98bd-771e2857d1f5.png)

**Comment by andrew** [comment]
Fixed that for you, will investigate why the was incorrectly marked as removed

**Comment by revelt** [comment]
thanks!
