### ISSUE TITLE
SSL is free on AWS, no need for Cloudflare

### ISSUE THREAD

**Issue by mslinn** [librariesio/support#134]
Your docs say "Unfortunately, https costs money especially when you want to just try out to see if something works. Fortunately for this we can use Cloudflare as the CDN to our AWS S3 website. Cloudflare also provides a free SSL certificate for free."

This is incorrect, AWS provides free [SSL certificates that automatically renew](https://aws.amazon.com/blogs/aws/new-aws-certificate-manager-deploy-ssltls-based-apps-on-aws/). There is no need for Cloudflare.

**Comment by andrew** [comment]
Have you got a link to those docs? I don't remember writing that

**Comment by mslinn** [comment]
https://libraries.io/github/opszero/buy-button#website

**Comment by andrew** [comment]
Ah, that repository is over here: https://github.com/opszero/buy-button
