### ISSUE TITLE
No Apache-Session

### ISSUE THREAD

**Issue by chorny** [librariesio/support#15]
I see that CPAN is used as a source, but I cannot find Apache-Session.

**Comment by chorny** [comment]
Found it by looking at http://libraries.io/cpan/Apache-Session. Still, I was not able to find it with search for Apache-Session and it is not shown that language is Perl (which should be evident as it was taken from CPAN - there are only several distributions that are not written for Perl).

**Comment by andrew** [comment]
Our search definitely needs improvement for CPAN, sorry about that.

I've updated Apache-Session with more information now, including the language: http://libraries.io/cpan/Apache-Session
