### ISSUE TITLE
Package releases inconsistent with npm

### ISSUE THREAD

**Issue by neogeek** [librariesio/support#16]
**libraries.io**

![screen shot 2015-03-22 at 5 55 26 pm](https://cloud.githubusercontent.com/assets/6753/6771723/94f152f8-d0bd-11e4-96a1-14071746592c.png)

**npm**

![screen shot 2015-03-22 at 5 57 57 pm](https://cloud.githubusercontent.com/assets/6753/6771725/99a9174a-d0bd-11e4-8760-3f7a3a5a2fd7.png)

**Comment by andrew** [comment]
Ah the wonders of the NPM API, those extra versions show up here: http://registry.npmjs.org/linear but 404 here: http://registry.npmjs.org/linear/0.5.0 so we'll need to do more checks when downloading modules

Thanks for the heads up @neogeek, I'll add it to the todo list.

**Comment by andrew** [comment]
That's been fixed for you now @neogeek: http://libraries.io/npm/linear

**Comment by neogeek** [comment]
:thumbsup: Thanks!
