### ISSUE TITLE
Source for libraries.io itself?

### ISSUE THREAD

**Issue by wking** [librariesio/support#18]
It seems odd to have a closed source tracker for open source libraries ;).  Is the engine behind libraries.io available somewhere?  None of the repositories listed under https://github.com/librariesio look like the main application.  I was looking for it so I could see how difficult it would be to add support for a language-agnostic package manager (apt, Portage, …) alongside the existing language-specific package managers (PyPI, npm, …).  I'd expect the biggest issue would be resolving conflicts between dependency requirements, since different packages for the same project don't always agree :p.

**Comment by andrew** [comment]
It's closed source partly due to not having the time to manage it as an open source project, that may change in the future though. System level package managers are on my todo list but I'm focusing on application level ones in the short term.

**Comment by wking** [comment]
On Fri, Mar 27, 2015 at 04:49:32AM -0700, Andrew Nesbitt wrote:
> It's closed source partly due to not having the time to manage it as
> an open source project, that may change in the future though. System
> level package managers are on my todo list but I'm focusing on
> application level ones in the short term.

If it was open source, you could shift the system-level package
managers to other folks' todo lists ;).  But it still takes time to
review contributions…
