### ISSUE TITLE
Received emails for all subscribed Cocoapod library releases

### ISSUE THREAD

**Issue by craigmarvelley** [librariesio/support#19]
I subscribed to a bunch of Cocoapod releases a few days ago, and last night I received an email for seemingly every historical release of each library.

**Comment by andrew** [comment]
Sorry about that @craigmarvelley, I had to reimport the cocoapod packages and forgot to disable emails for people already subscribed to them, I've taken steps to ensure that won't happen again.

**Comment by craigmarvelley** [comment]
Not a problem! I got to feel really popular for a bit, until I checked what
had swelled my inbox :) Cheers
