### ISSUE TITLE
Option to notify only on major, minor, tiny or development releases

### ISSUE THREAD

**Issue by wadtech** [librariesio/support#20]
This may relate more directly to packagist but may apply generally.

Following active projects on packagist can be a bit punishing on the notification front. For example laravel/laravel has many development commits as it is an active project.

Packagist tracks dev-master as the current development 'release' and so libraries.io sends an alert for each update of that as well as actual point releases.

It would be nice to be able to specify what level of notification to receive per package, each push to packagist can generate 3 or 4 alerts at a time.

**Comment by andrew** [comment]
Yeah I think we'll stop alerting/updating dev-master at all for packagist, which seems to be the exception, it doesn't match any kind of semver either!

**Comment by wadtech** [comment]
dev-master is mostly used when you're pretty lose about a dependency, for instance when starting a project before locking to usually the latest release specifically.

You wouldn't generally expect to track any sort of actual release with it, so I think that would be fine.

**Comment by andrew** [comment]
@wadtech You shouldn't get notified of any `dev-*` releases now and they are being hidden from the site for the moment as well.

**Comment by wadtech** [comment]
:+1:
