### ISSUE TITLE
redirect_uri_mismatch when subscribing to updates on https://libraries.io

### ISSUE THREAD

**Issue by wadtech** [librariesio/support#23]
http://libraries.io/auth/failure?message=redirect_uri_mismatch&origin=https%3A%2F%2Flibraries.io%2Fnpm%2Fjohnny-five&strategy=github

encountered when subscribing to updates on https://libraries.io/npm/johnny-five presumably attempting to call back to http://

**Comment by andrew** [comment]
This should be fixed now, all logins will be via SSL and I'll be switching the whole site to SSL this week.
