### ISSUE TITLE
Include platform.io

### ISSUE THREAD

**Issue by beriberikix** [librariesio/support#24]
https://github.com/platformio/platformio is a reletively new package manager for embedded development (Arduino, ARM, etc.) There's an API for their database: https://github.com/platformio/platformio-api

**Comment by andrew** [comment]
Done! https://libraries.io/platformio

**Comment by beriberikix** [comment]
:clap: that's basically the fastest fix I've ever seen!

**Comment by andrew** [comment]
Yeah, package managers with a nice Json api are really easy to add!
