### ISSUE TITLE
Add a subtome button for RSS feeds 

### ISSUE THREAD

**Issue by lloydwatkin** [librariesio/support#26]
**Description:**
Universal Follow Button
SubToMe makes it easy for people to follow web sites,
because browsers don't do it."

**Integration (is easy):**
http://docs.subtome.com/developers/

**Link:**
https://www.subtome.com/#/

cc: @julien51

**Comment by julien51** [comment]
:+1:

**Comment by andrew** [comment]
Looks handy, I'll see if I can hook it onto the existing orange rss buttons this evening.

**Comment by andrew** [comment]
All the orange rss feed buttons are now hooked up with subtome :+1:

**Comment by lloydwatkin** [comment]
\o/
