### ISSUE TITLE
Subscribe to Stable Releases

### ISSUE THREAD

**Issue by rodnaph** [librariesio/support#27]
(Apologies if I've missed the option for this, but...) Is there a way to only receive notifications for releases of stable versions of my subscriptions?

For example I'm subscribed to 'symfony/symfony' and get notifications about all the *-dev releases, when I'm only really interested in stable releases.

**Comment by andrew** [comment]
No you didn't miss anything, that feature isn't there yet, I'll add it to my todo list and let you know when it's shipped.

**Comment by piether** [comment]
I just got a notification for a release of angular 1.3.19. I only care for (stable) releases on version 1.4 and up.

So I think it would be nice if a user could also indicate that sort of preference.

**Comment by andrew** [comment]
@piether yeah that makes sense to have that as a default, only notifying you of new releases since you've subscribed and opt-in to pre-releases as well

**Comment by knolleary** [comment]
:+1: 

As well as being able to subscribe to only particular version streams (ie, only updates to the 1.4 stream), it would great to be able to chose to ignore packages that have 'alpha' or 'beta' in their version string. One of the Node-RED deps is up to it's 30th alpha release on npm and just made a start on their beta releases. We won't look at it until it's stable.

**Comment by andrew** [comment]
I've finally got round to adding an option to mute prerelease version notifications, you'll find it in a dropdown on the right on the subscribe button on every project: 
![screen shot 2016-02-25 at 8 03 35 am](https://cloud.githubusercontent.com/assets/1060/13313510/7084b182-db96-11e5-9660-96286ddb25ab.png)
