### ISSUE TITLE
correct case of GitHub in footer

### ISSUE THREAD

**Issue by pborreli** [librariesio/support#3]
In http://libraries.io/ 's footer `Github` should be written `GitHub`

:bow:

**Comment by andrew** [comment]
Fixed, thanks @pborreli!

**Comment by pborreli** [comment]
wow that was fast :speedboat: , thanks ! :clap:

**Comment by pborreli** [comment]
btw, there are other place `Github` is used with bad casing, like for example in title of http://libraries.io/github/substack page:
> Github repositories owned and contributed by James Halliday

**Comment by andrew** [comment]
Fix

**Comment by andrew** [comment]
Fixed that one too
