### ISSUE TITLE
Disabling email notifications

### ISSUE THREAD

**Issue by Kreozot** [librariesio/support#34]
I don't want to recieve email everytime when some of my packages was updated. I just want to check it sometimes by myself. When count of your packages more than 20. emails are beginning to be really annoying. But for now I have just two options - subscribe or unsubscribe. Sad.

**Comment by andrew** [comment]
@Kreozot I'm working on a daily/weekly digest email which should help reduce the number of emails your getting

**Comment by andrew** [comment]
You can turn off email notifications now, fixed along with https://github.com/librariesio/libraries.io/issues/182 and https://github.com/librariesio/support/issues/78
