### ISSUE TITLE
Email notifications to custom email

### ISSUE THREAD

**Issue by JoeStanton** [librariesio/support#35]
It'd be great to get email notifications to an email address not tied to GitHub. We have email distribution lists for all developers on each project, and it'd be useful to route all update notification emails there instead.

**Comment by andrew** [comment]
@JoeStanton I've added a form so you can edit the email on your account here: https://libraries.io/account

In future there will be a way to add multiple emails to your account but this should help for now.

**Comment by JoeStanton** [comment]
Brilliant, just added our team email. Thanks!

**Comment by JoeStanton** [comment]
Unfortunately this seems to be reset when I next log in. I take it you're probably updating the email based on the GitHub API info.

**Comment by andrew** [comment]
D'oh! Yeah looking into it now it just blanket updates all github details each time you log in, I'll fix this up tomorrow.

**Comment by andrew** [comment]
@JoeStanton sorry for the delay, moving house to an area with no 3g signal or wifi slightly slowed my progress down, back online now and just rolled out a fix so your update email won't be changed after you login again :feelsgood:

**Comment by JoeStanton** [comment]
Nice one, I'll check it out! :dancer:
