### ISSUE TITLE
Contributors URL in Project Statistics of site points at "/stargazers" not "/contributors"

### ISSUE THREAD

**Issue by Ogreman** [librariesio/support#36]
Side bar of project page [example (Django)](https://libraries.io/pypi/Django) lists the following:
* Stars	    W
* Forks	     X
* Watchers	     Y
* Contributors  Z	

The URL (on Z) for a project's contributors points at GitHub's stargazers and not its contributors.

Expected: https://github.com/[user]/[repo]/graphs/contributors
Actual: https://github.com/[user]/[repo]/stargazers

**Comment by andrew** [comment]
Good spot @Ogreman, I've just deployed a fix for that, the contributors number should link to the right place now

**Comment by Ogreman** [comment]
Speedy! Tested and it's working as expected. Nice one, @andrew.
