### ISSUE TITLE
Wonky CSS on https://libraries.io/subscriptions

### ISSUE THREAD

**Issue by beriberikix** [librariesio/support#41]
![screen shot 2015-09-08 at 7 35 45 am](https://cloud.githubusercontent.com/assets/178376/9737626/5c3d1ad6-55fc-11e5-879d-8d48721fda99.png)

This is what I see on standard zoom. Feels like it is stuck halfway between media queries.

OSX X Yosemite 10.10.5
MacBook Air (13-inch, Mid 2013)
Cr 45.0.2454.85 (64-bit)

**Comment by andrew** [comment]
Just rolled some tweaks, should be good now

**Comment by beriberikix** [comment]
:+1:
