### ISSUE TITLE
Quality of Recommendation

### ISSUE THREAD

**Issue by sirinath** [librariesio/support#42]
The recommendation presented as you login are projects I would be least interested in. It would be good to customise this based on the user's projects, stars, watching, etc.

**Comment by andrew** [comment]
Hi @sirinath, thanks for the feedback, you discovered it at a very early stage, I'm making ongoing improvements to the recommendation engine and feeding in more GitHub data all the time.

Expect to see better recommendations showing up over the coming weeks.
