### ISSUE TITLE
Missing project repo

### ISSUE THREAD

**Issue by terrytangyuan** [librariesio/support#43]
I have a R project on Github published on CRAN. I can find it from my profile but cannot find it from R language category to CRAN category.

**Comment by terrytangyuan** [comment]
Specifically, the following two repos:

https://github.com/terrytangyuan/lfda
and https://github.com/terrytangyuan/dml

**Comment by andrew** [comment]
Hi @terrytangyuan, your packages are here https://libraries.io/cran/dml and https://libraries.io/cran/lfda, I'm working on making them easier to discover from the CRAN and R category pages.

**Comment by terrytangyuan** [comment]
Yeah they exist but I cannot find them through the search engine, e.g. 
```
https://libraries.io/search?q=lfda&platforms=CRAN&languages=R
or 
https://libraries.io/search?q=dml&platforms=CRAN&languages=R
```

**Comment by andrew** [comment]
Sorry about that @terrytangyuan, there was a bug with indexing CRAN projects, the language didn't show up correctly, I've just reindexed them and they are now showing up for your searches.

**Comment by terrytangyuan** [comment]
@andrew no worries. Thanks.
