### ISSUE TITLE
Prune removed tags

### ISSUE THREAD

**Issue by tarsius** [librariesio/support#45]
It seems that you are not pruning tags that have been removed from the upstream repository.

The `90150116` tag on https://libraries.io/emacs/magit is an example of that. Or maybe you generally prune tags but this one somehow survived. At least this one should be deleted - it's a snapshot tag which was necessary to work around limitations in melpa and melpa-stable. Now that I regularly create releases such snapshot tags are no longer required.

**Comment by andrew** [comment]
Thanks for letting me know @tarsius, I've removed that old tag on magit for you.

I'm not currently pruning tags as Libraries is tracking over 15 million tags and I don't have the server capacity to check them all on a regular basis just yet!

**Comment by tarsius** [comment]
Thank you.
