### ISSUE TITLE
Removing a tracked repository

### ISSUE THREAD

**Issue by Boubalou** [librariesio/support#46]
Is there a way to remove a repository that was tracked from NPM? The repo went public for 2mins, you guys indexed it but then got moved to a private repo.

It is mandatory for us to not let this one go public, but it is exposed from librairies.io at the very moment.

Please, it would be very cool if you guys would at least see a repo twice or trice before assuming it to be a repo to present in Librairies.io.

Now we are fudged with an indexing issue in google as well.

**Comment by andrew** [comment]
@Boubalou I've removed that for you now, you can add `"private": true` in `package.json` to avoid accidentally publishing modules to npm in future.

**Comment by Boubalou** [comment]
:+1:
