### ISSUE TITLE
Tag sorting

### ISSUE THREAD

**Issue by neogeek** [librariesio/support#48]
Tags (as seen [here](https://libraries.io/github/neogeek/doxdox) and attached screenshot) are sorted incorrectly.

<img width="266" alt="screen shot 2015-11-03 at 3 00 08 pm" src="https://cloud.githubusercontent.com/assets/6753/10920064/32faeb3c-823c-11e5-8d61-0fbd6690f508.png">

**Comment by andrew** [comment]
Sorry about that, just deployed a change to sort the by publish date from newest to oldest, should show up soon once the cache expires.

**Comment by neogeek** [comment]
Cool, thanks!
