### ISSUE TITLE
Difference in stats for stars and forks in https://github.com/krazedkrish/select-multiple

### ISSUE THREAD

**Issue by krazedkrish** [librariesio/support#52]
Hi!

Firstly, thanks for an awesome library to analyse github opensource contributions.

I noticed that the page https://libraries.io/github/krazedkrish/repositories is showing less stars and less forks than the actual stat. What can be done to sync them?

**Comment by andrew** [comment]
Hi @krazedkrish 

I've updated your list of repos, we're always a little bit behind but I've made some recent changes that should help keep star/fork counts more up to date, you can also login with your github repository and enable repository tracking from https://libraries.io/repositories which will do a full update of all your repos at least once per day.

**Comment by krazedkrish** [comment]
thanks @andrew!
