### ISSUE TITLE
Easier unmuting of muted libraries

### ISSUE THREAD

**Issue by danielthepope** [librariesio/support#53]
After signing in, I muted a library from the libraries.io homepage/news feed, then I was expecting to be able to unmute it from https://libraries.io/?include_muted=true, but that page will just try muting it again.

Instead I had to go to the [library page](https://libraries.io/npm/electron-debug) and unmute it from there.

**Comment by andrew** [comment]
Yeah you're right, I'll put a page together that lists all the muted projects.

**Comment by andrew** [comment]
@danielthepope I've just added a page for you, listing all of the projects that you've muted, with a button to quickly unmute any of them: https://libraries.io/muted
