### ISSUE TITLE
Scoped npm packages

### ISSUE THREAD

**Issue by achingbrain** [librariesio/support#54]
Is it possible to see scoped npm packages on libraries.io?

E.g. this exists: https://www.npmjs.com/package/@achingbrain/ssdp but this doesn't: https://libraries.io/npm/@achingbrain/ssdp

**Comment by andrew** [comment]
I investigated this a little while back for @keithamus, some of the end points are there, like http://registry.npmjs.org/@achingbrain%2fssdp but not the ones for particular versions which return blank responses: http://registry.npmjs.org/@achingbrain%2fssdp/0.0.1

It should be possible to pull most of the info from `http://registry.npmjs.org/@achingbrain%2fssdp` so I can update the script to find that, but the other problem is discovery, as far as I can tell, npm don't scoped packages anywhere for libraries to find them, so it would be a case of only discovering them if they were depended upon by other library/repo first.

**Comment by andrew** [comment]
Just ran some stats across the libraries database for npm dependencies where the package name starts with `@`: https://gist.github.com/andrew/53d31ec7a6995a630d12

Total public scoped packages: 843
Total users who published public scoped packages: 304
Total published npm modules dependent on public scoped packages: 587
Total scoped modules depended upon by open source github repos: 599
Total open source github repos dependent on public scoped packages: 1105 (944 not forks)
Total github users/orgs depending upon public scoped packages: 412

It's on the TODO list to support but there are a few other more pressing things to work on given how little usage public scoped packages have on npm.

**Comment by achingbrain** [comment]
> as far as I can tell, npm [doesn't list] scoped packages anywhere for libraries to find them

I guess that might be linked to npm/npm#8244?  Anyway, thanks for looking into it, libraries is amazing.

**Comment by zeke** [comment]
@andrew this is really useful information. Thanks for digging!

**Comment by keithamus** [comment]
It doesn't surprise me that there are so few public scoped packages - the root namespace is still not completely full, and suffers from the same kind of problem as .com domains - exposure/discoverability is definitely not the strength of scoped packages.

Their main selling point is that they can be private packages. For example I have around 100 private scoped packages which if you try to hit via the API without a valid token, then npm returns a 404. I guess those aren't listed in your stats.

A a number I just pulled out of my ass - I'd expect npm private packages to be in the thousands, if not tens of thousands. I'd agree that its probably not a priority for libaries.io for now - but they're definitely something to keep an eye on.

**Comment by andrew** [comment]
🚢  https://libraries.io/npm/@shoutem%2Fcore

**Comment by achingbrain** [comment]
Woohoo! Thanks so much.

**Comment by zeke** [comment]
@andrew are you using the new replicate.npmjs.com endpoint?

https://github.com/npm/registry/issues/37

**Comment by andrew** [comment]
@zeke nope

**Comment by vvo** [comment]
@andrew How do you watch for changes on the npm registry including scoped public packages?

**Comment by andrew** [comment]
@vvo haphazardly by looking at what people reference on github: https://github.com/shoutem/ui/blob/develop/package.json#L6
