### ISSUE TITLE
Get a list of the modules which were removed from npm and have dependents.

### ISSUE THREAD

**Issue by ankurkaushal** [librariesio/support#55]
According to [this tweet](https://twitter.com/teabass/status/667366068147642369), @andrew found 7000 node modules that have been removed from npm and have around 1000 dependents. 

It would be great if there's a list of those modules and we let the new developers pick the ones they want to work on (like me) & that list may also serve as an repository of ideas for node modules. 

What say?

**Comment by andrew** [comment]
@ankurkaushal I've finally got round to doing this, there are two new pages on the site to give you lists of removed and deprecated libraries, both of which can be filtered by package manager too:

- https://libraries.io/removed-libraries
- https://libraries.io/deprecated-libraries
