### ISSUE TITLE
"Dependent packages" do not work with Python

### ISSUE THREAD

**Issue by untitaker** [librariesio/support#56]
See title. E.g. if you look at [vdirsyncer](https://libraries.io/pypi/vdirsyncer), you'll see that it depends on [atomicwrites](https://libraries.io/pypi/atomicwrites). However, vdirsyncer is not listed as "Dependent package" at the page for `atomicwrites`.

Is cloning the repo, and evaluating `setup.py` using `ast.literal_eval` from Python's stdlib a possible implementation for you?

**Comment by andrew** [comment]
Thanks @untitaker, yeah that looks like the right thing to do, for each version of the package I'll need to download each tarball and run it, might take me a little while

**Comment by untitaker** [comment]
Note that `literal_eval` is not like eval, it is "safer", but isn't suitable for everything that a `setup.py` can do (like, conditionally constructing a list of dependencies)

**Comment by whit537** [comment]
> evaluating `setup.py` using `ast.literal_eval`

I was thinking of somehow hooking the `setup` function inside `setup.py` to intercept the values for `install_requires`, etc. actually passed in. I've started work towards a PyPI metadata crawler in https://github.com/gratipay/gdr.rocks/issues/2 and https://github.com/gratipay/gdr.rocks/issues/5. I'd be interested in contributing that work to Libraries.io if interested.

P.S. I believe https://github.com/librariesio/libraries.io/issues/362 overlaps with this ticket.

**Comment by andrew** [comment]
That sounds great, getting this working for python is a goal of mine for this year.

**Comment by untitaker** [comment]
As far as I understand stubbing setup doesn't solve the problem of evaling untrusted code, but it is probably the most flexible solution.

On 20 October 2016 03:28:31 CEST, Chad Whitacre <notifications@github.com> wrote:
>> evaluating `setup.py` using `ast.literal_eval`
>
>I was thinking of somehow hooking the `setup` function inside
>`setup.py` to intercept the values for `install_requires`, etc.
>actually passed in. I've started work towards a PyPI metadata crawler
>in https://github.com/gratipay/gdr.rocks/issues/2 and
>https://github.com/gratipay/gdr.rocks/issues/5. I'd be interested in
>contributing that work to Libraries.io if interested.
>
>P.S. I believe https://github.com/librariesio/libraries.io/issues/362
>overlaps with this ticket.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/librariesio/support/issues/56#issuecomment-254986071

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by whit537** [comment]
> stubbing setup doesn't solve the problem of evaling untrusted code

Yeah, for that I've been using Docker, seems to work a treat.

**Comment by whit537** [comment]
Is extracting Python dependency data the only place in Libraries.io that requires running untrusted code? If not, then that part of the infrastructure could/should probably be generalized. Maybe it already has been?

**Comment by andrew** [comment]
This has been implemented now but is taking a while to backfill for all python libraries but data is starting to show on the site: https://libraries.io/pypi/requests/dependents
