### ISSUE TITLE
Deleted GitHub repositories still show up in Libraries.io

### ISSUE THREAD

**Issue by sykaeh** [librariesio/support#57]
I noticed that repositories that have been deleted on GitHub still show up on Libraries.io. One such example is: https://libraries.io/github/sykaeh/pyv8

Is this intentional? I would find it helpful if they would also be removed from Libraries.io or have some indication that the repository no longer exists.

**Comment by andrew** [comment]
@sykaeh I've added a big warning to any GitHub repository that's been removed, it might not show up the instant you delete a project but if libraries checks it and finds it missing it will be update: 
<img width="612" alt="screen shot 2015-12-27 at 7 37 19 pm" src="https://cloud.githubusercontent.com/assets/1060/12011724/6b7e5376-acd1-11e5-899f-566b471fa1ea.png">
