### ISSUE TITLE
Unlisted Nuget Repo with 1900 Dates

### ISSUE THREAD

**Issue by JeremyNevill** [librariesio/support#58]
Just undertaken a search to work out the best chromedriver Nuget package to use.  

Interestingly the top result is shown as unlisted on Nuget and the 1900 dates give a '116 years ago' updated value on the search results.

Not bugs per se but worth noting in case you add a feature to show retired packages.

**Comment by andrew** [comment]
Ah I didn't know that nuget had an unlisted feature, thanks for that, I'll update the nuget download to mark  unlisted projects as such. I'm also going to tweak the search algo to avoid highlighting very old packages!

**Comment by JeremyNevill** [comment]
No worries, an unlisted feature would be good and handy if they were bumped from the recommended packages, thanks!

**Comment by andrew** [comment]
@JeremyNevill All the unlisted nuget packages are now hidden from search results.
