### ISSUE TITLE
Request to add logo to Pub listing

### ISSUE THREAD

**Issue by sethladd** [librariesio/support#6]
Thanks for including Pub!

Can you include this logo: https://www.dartlang.org/logos/dart-logo.png

 (right now, there's a gray box next to the word Pub on http://libraries.io/pub)

**Comment by andrew** [comment]
cc @olizilla

**Comment by olizilla** [comment]
:+1 on it

**Comment by olizilla** [comment]
Fixed! 
![screenshot 2015-03-17 00 15 48](https://cloud.githubusercontent.com/assets/58871/6679074/d984fa1e-cc3a-11e4-8775-2e14f5b557ca.png)

**Comment by andrew** [comment]
@olizilla I think the pub logo is the same as the dart logo as well.

**Comment by olizilla** [comment]
Egads. Should have read the issue! Is fixed for both now.

**Comment by andrew** [comment]
:pray:
