### ISSUE TITLE
Releases of a project not in sync

### ISSUE THREAD

**Issue by alexconlin** [librariesio/support#61]
I just checked a library that I use and the releases on the page on libraries.io does not match the latest releases in maven central or in github for the library?

The library is restfb and on this page: https://libraries.io/maven/com.restfb:restfb it shows the latest release as 1.14.0 but on maven central and github it is up to 1.18.1:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.restfb%22%20AND%20a%3A%22restfb%22
and
https://github.com/restfb/restfb

**Comment by andrew** [comment]
Hi @alexconlin, sorry about that, I've updated that library for you now, my maven support is still a little lacking as it's quite a tricky beast to get good timely data out of!

**Comment by alexconlin** [comment]
Thanks @andrew :)
