### ISSUE TITLE
Addition of missing maven projects to the index

### ISSUE THREAD

**Issue by rhyshort** [librariesio/support#63]
There are few open source maven projects in the com.cloudant group missing from the index,

They are:

[cloudant-sync-datastore-core](
http://mvnrepository.com/artifact/com.cloudant/cloudant-sync-datastore-core)
[Cloudant-Sync-Datastore-android](http://mvnrepository.com/artifact/com.cloudant/cloudant-sync-datastore-android)
[cloudant-sync-datastore-android-encryption](http://mvnrepository.com/artifact/com.cloudant/cloudant-sync-datastore-android-encryption)
[cloudant-sync-datastore-javase](http://mvnrepository.com/artifact/com.cloudant/cloudant-sync-datastore-javase)

**Comment by arend-von-reinersdorff** [comment]
Checked today, three of the four libraries are present in libraries.io:
[cloudant-sync-datastore-core](https://libraries.io/maven/com.cloudant:cloudant-sync-datastore-core)
[cloudant-sync-datastore-android-encryption](https://libraries.io/maven/com.cloudant:cloudant-sync-datastore-android-encryption)
[cloudant-sync-datastore-javase](https://libraries.io/maven/com.cloudant:cloudant-sync-datastore-javase)
Although not quite up to date:
Latest version in libraries.io: 0.15.1 - 25-Jan-2016
Later versions in Maven Central starting from: 0.15.2 - 04-Feb-2016

Still not present:
[cloudant-sync-datastore-android](https://libraries.io/maven/com.cloudant:cloudant-sync-datastore-android)

**Comment by andrew** [comment]
I've updated those for you now, and am working on an improved maven crawler to help improve the speed of updates in the future.
