### ISSUE TITLE
How to update username

### ISSUE THREAD

**Issue by danhayden** [librariesio/support#64]
I have updated my username on GitHub and was wondering how I reflect this change on libraies.io?

My current profile is https://libraries.io/github/pythonic1 and my new username on GitHub is danhayden

Thanks for your help :)

**Comment by andrew** [comment]
Hey Dan

I've updated your username, the old one is cached in some repo names across
the site so it might take a little while for all those links to update but
your profile now works: https://libraries.io/github/danhayden

Cheers
Andrew

**Comment by danhayden** [comment]
Thanks for the quick response and fix. Great work as always :)
