### ISSUE TITLE
PureScript package support

### ISSUE THREAD

**Issue by AppShipIt** [librariesio/support#68]
Continued from [Twitter](https://twitter.com/librariesio/status/700359678648258560). [PureScript](http://www.purescript.org) packages are stored in [Pursuit](https://pursuit.purescript.org) maintained by @hdgarrood. Its API is:
```
Accept: application/json
GET /packages
GET /packages/purescript-{package}/available-versions
```
PureScript is a [popular](https://libraries.io/github/purescript/purescript) strongly typed, purely functional programming language, inspired by Haskell which compiles to readable JavaScript with a simple foreign interoperability.

**Comment by andrew** [comment]
I'm pondering how best to implement this, as all the package manager for purescript is just bower, which is already supported, you can see all the packages here: https://libraries.io/search?languages=PureScript&platforms=Bower

There's also the Purescript language page which includes a few more available in npm: https://libraries.io/languages/PureScript

One idea I've been pondering is the ability to create collections of projects which seems like a good fit for that, and if it had an api then it could be programmatically added from the Pursuit API.

So it would end up looking something like a page on /collections/Pursuit, similar to the language page, with a list of all the packages from the website?

**Comment by hdgarrood** [comment]
That's a good point actually - we should probably clarify, what do we want from purescript package support that we don't already have? I can't think of anything.

**Comment by AppShipIt** [comment]
Huh that's my bad I've never thought to use the site independent of a package manager. I suppose the only missing feature is a link to documentation on Pursuit? Amazing work all around!

**Comment by hdgarrood** [comment]
Most packages already include links to pursuot in their readmes, so I'm not sure if we need that, even.

**Comment by AppShipIt** [comment]
If you look at the Elm packages there's already a place for it in the UI.

**Comment by andrew** [comment]
@AppShipIt I've added a documentation link to Pursuit for any Bower package where the language is PureScript, for example: https://libraries.io/bower/purescript-ace-halogen

<img width="591" alt="screen shot 2016-02-22 at 10 56 27 am" src="https://cloud.githubusercontent.com/assets/1060/13216339/193ac4d8-d953-11e5-9f73-4220e5593f80.png">

**Comment by AppShipIt** [comment]
Epic case closed 🙏

**Comment by andrew** [comment]
:fireworks:
