### ISSUE TITLE
Don't want to see beta versions

### ISSUE THREAD

**Issue by ivanoats** [librariesio/support#69]
I'm getting quite a few emails about beta versions of packages. I'd prefer not to see the beta versions, just releases. Is there any way to unsubscribe from the beta versions?

**Comment by andrew** [comment]
@ivanoats I've just added an option to mute prerelease version notifications, you'll find it in a dropdown on the right on the subscribe button on every project: 
![screen shot 2016-02-25 at 8 03 35 am](https://cloud.githubusercontent.com/assets/1060/13313510/7084b182-db96-11e5-9660-96286ddb25ab.png)
