### ISSUE TITLE
Add Vala programming language

### ISSUE THREAD

**Issue by tpimh** [librariesio/support#7]
Subj. It's kind of popular nowadays https://github.com/search?l=Vala&p=5&q=language%3AVala&ref=advsearch&type=Repositories&utf8=%E2%9C%93

**Comment by andrew** [comment]
All the data is currently pulled from package managers, are there any Vala package managers I can pull data from?

**Comment by tpimh** [comment]
I am not sure. There is something like package manager (http://www.tarnyko.net/dl/valawinpkg.htm), but it is probably not what you want.
valadoc.org has a list of libraries (not complete) for Vala.

**Comment by andrew** [comment]
@tpimh you can now browse Vala Github repos here: https://libraries.io/github?language=Vala
