### ISSUE TITLE
PlatformIO: Replace our ugly library URL

### ISSUE THREAD

**Issue by ivankravets** [librariesio/support#72]
We have switched from ugly to pretty URL today. Please update `View on registry:` link.

For example, https://libraries.io/platformio/Json

```
from 
http://platformio.org/#!/lib/show/64/Json
to
http://platformio.org/lib/show/64/Json
```

Thanks.

**Comment by andrew** [comment]
Fixed! Thanks for letting me know @ivankravets :snowboarder:

**Comment by ivankravets** [comment]
Thanks a lot @andrew .

P.S: Do you have any ideas as for https://github.com/librariesio/support/issues/73? We have tried to use your service via IFTTT > Slack :) Looks very useful but doesn't report all libs :(
