### ISSUE TITLE
RSS feed doesn't contain all libs

### ISSUE THREAD

**Issue by ivankravets** [librariesio/support#73]
I subscribed to a few libs. However, `https://libraries.io/home.atom?api_key=***` doesn't contain the latest updated libs.

Please correct me to other link if it is wrong.

**Comment by andrew** [comment]
Sorry for the delay @ivankravets, I've got an issue open for it here: https://github.com/librariesio/libraries.io/issues/410

The homepage activity feed only shows updates for package managers that have proper support for versions, package managers like Bower and Go currently fallback to git tags which are not currently shown in the homepage feed or rss, definitely a bug.

**Comment by ivankravets** [comment]
Thanks for the info. I subscribed to #410
