### ISSUE TITLE
Pagination Error after page 100

### ISSUE THREAD

**Issue by eurica-larazo** [librariesio/support#76]
Returns 404 page when accessing the pages above 100.
https://libraries.io/api/search?page=101&platforms=Go&api_key=API_TOKEN

**Comment by andrew** [comment]
Pagination is currently capped at 100 pages across the whole site to avoid putting excess load on the server and database here: https://github.com/librariesio/libraries.io/blob/master/app/controllers/application_controller.rb#L15

How many pages are you wanting to load?

**Comment by eurica-larazo** [comment]
I actually wanna load all of them to generate programming related tags.

**Comment by andrew** [comment]
@eurica-larazo I've increased the `per_page` limit to 1000 for API responses, hope that helps
