### ISSUE TITLE
The "pub manager" marked as supported the tags but the "pub manager" does not support tags

### ISSUE THREAD

**Issue by mezoni** [librariesio/support#77]
[Here](https://libraries.io/about) the "pub manager" marked as it suports the tagging but the "pub manager" does not support tags.

How them (tags) works on libraries.io with the pub?
It would be interesting to see.

**Comment by mezoni** [comment]
Support is temporarily unavailable?

**Comment by andrew** [comment]
@mezoni sorry about that, pub doesn't have tag support, just regular versions, I've updated that page now.
