### ISSUE TITLE
Allow disabling of email notifications

### ISSUE THREAD

**Issue by michaelmior** [librariesio/support#78]
It's convenient to be able to log in to the site and see a list of recently updated packages I'm interested in. However, I don't really want to receive email about every new release. There doesn't currently seem to be an option to disable sending emails.

**Comment by andrew** [comment]
@michaelmior I've just deployed an option in the account settings to disable emails: https://libraries.io/account

**Comment by michaelmior** [comment]
Awesome! Thanks.
