### ISSUE TITLE
Hosting bower search

### ISSUE THREAD

**Issue by sheerun** [librariesio/support#79]
Hey,

Would you consider hosting bower search functionality? https://bower.io/search

If you agreed, it probably would require lifting api limit though :)

Adam

**Comment by andrew** [comment]
@sheerun absolutely, I'm beefing up the API as we speak as a number of other projects have asked for increased rate limits too, can you drop me an email at andrew@libraries.io to discuss?

**Comment by andrew** [comment]
🚢
