### ISSUE TITLE
"Updated pub packages" is not up to date

### ISSUE THREAD

**Issue by sethladd** [librariesio/support#8]
As of Mar 16th:

![screen shot 2015-03-16 at 12 24 32 pm](https://cloud.githubusercontent.com/assets/5479/6674512/797e1280-cbd7-11e4-8cb0-7fb8d4dee992.png)

![screen shot 2015-03-16 at 12 24 21 pm](https://cloud.githubusercontent.com/assets/5479/6674516/80f39de6-cbd7-11e4-85f7-b86e2eb327cb.png)

**Comment by andrew** [comment]
I *may* have accidentally deleted the crontab entry for pub ~3 days ago, I've just imported the latest projects and re-added the background task, sorry about that!

**Comment by sethladd** [comment]
thanks
