### ISSUE TITLE
Pagination in API requests

### ISSUE THREAD

**Issue by ogaleac** [librariesio/support#83]
Hi,

I am doing API calls to search for "web-component" and "web-components", but it appears that there is a problem with the pagination because, for any page requested I always get the same result back. For example:

https://libraries.io/api/search?q=web-component&page=2
https://libraries.io/api/search?q=web-component&page=3

return the same. A few weeks ago, the URL were returning different results, but now they return the same.

Thanks

**Comment by raquelsa** [comment]
I am also running into this issue. Any updates on this? Thanks!

**Comment by andrew** [comment]
I'm away on holiday at the moment, will get it fixed up as soon as I get back on Friday

**Comment by andrew** [comment]
@ogaleac @raquelsa for a short term fix you can add `&per_page=30`, ie: https://libraries.io/api/search?q=web-component&page=2&per_page=30 

I'll get it properly sorted out as soon as I get home tonight, sorry for the delay

**Comment by andrew** [comment]
Just deployed a fix for that now.
