### ISSUE TITLE
Wrong order of beta releases

### ISSUE THREAD

**Issue by danez** [librariesio/support#91]
https://libraries.io/npm/webpack

beta.9 is ranked top, although beta.17 should be on top.

**Comment by danez** [comment]
Same issue here https://libraries.io/homebrew/watchman
4.6.0 is not considered the latest version although it is.

**Comment by andrew** [comment]
Looks like a bug in `Semantic::Version`: https://github.com/jlindsey/semantic/issues/12

This pr might fix it, I'll give it a go: https://github.com/jlindsey/semantic/pull/17

**Comment by andrew** [comment]
That fork looks like it works: 
![screen shot 2016-07-18 at 10 46 10 am](https://cloud.githubusercontent.com/assets/1060/16911182/e6dcf506-4cd4-11e6-81b5-8276c5bfb751.png)

Watchmen isn't quite the same as there's no dot between the `rc` and the number so it's ordered alphabetically.

**Comment by andrew** [comment]
Will deploy a new release shortly

**Comment by andrew** [comment]
Just deployed that and updated webpack: https://libraries.io/npm/webpack 

There's lots of caching on the site so it might take a few days for all of the version ordering to update. 

Thanks for reporting 🎉

**Comment by danez** [comment]
Thanks a lot.
What about the other watchman case? Is this also fixes with this update? At least that 4.6 is > than any of the RCs

**Comment by danez** [comment]
Oh just saw that 4.6 is now the latest 🎊 Thanks a lot

**Comment by andrew** [comment]
I'm currently running a background script to update the latest version number on about 67,000 projects that have a `-` in their version, might take a little while for everything to update.
