### ISSUE TITLE
SourceRank does not consider README and LICENSE with extension in name

### ISSUE THREAD

**Issue by martincostello** [librariesio/support#95]
Whatever populates the scores that make up SourceRank, it does not appear to find README and LICENSE files unless they are named exactly ```README``` and ```LICENSE```.

For instance, I have a [repository](https://github.com/martincostello/sqllocaldb) where the files are named ```license.txt``` and ```readme.md``` which are not picked up in its [SourceRank score](https://libraries.io/nuget/System.Data.SqlLocalDb/sourcerank).

**Comment by andrew** [comment]
@martincostello the problem with your project was that Libraries.io failed to connect the dots between the nuget project and the github repository, I fixed that and it found both the license and the readme.
