### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by zeke** [librariesio/support#99]
I'm getting 504 (Gateway Timeout) responses from the API, with or without an API key.

I have been limiting my requests to 1req/sec in my code, so I don't think I'm getting throttled?

**Comment by andrew** [comment]
The database is having issues as it's completely pegged on resources, will be upgrading soon but there may be errors for now :/

**Comment by zeke** [comment]
Is 1 req/sec still a responsible request rate?

**Comment by andrew** [comment]
👍 something is hitting it hard early in the morning UTC which is causing intermittent errors, new database machine should be online this weekend which will help a lot

**Comment by millette** [comment]
Been seeing 504s too for the last 30 minutes or so (I don't call the API often, don't know when it started).

**Comment by andrew** [comment]
There's a high load at the moment, the app server is still up but there may be some timeouts, hoping to get it fixed by tomorrow morning (uk time)

**Comment by whit537** [comment]
Can be closed?
